index_default:
    path: /
    requirements:
        _locale: "%locales%"
    controller: App\Controller\IndexController::index_default

index:
    path: /{_locale}
    requirements:
        _locale: "%locales%"
    controller: App\Controller\IndexController::index

single_category:
    path: /{_locale}/category/{slug}
    requirements:
        _locale: "%locales%"
    controller: App\Controller\CategoryController::singleCategory

single_category_with_subcategory:
    path: /{_locale}/category/{subcategoryslug}/{slug}
    requirements:
        _locale: "%locales%"
    controller: App\Controller\CategoryController::singleCategoryWithSubCategory

single_product:
    path:
        /{_locale}/product/{slug}
    requirements:
        _locale: "%locales%"
    controller: App\Controller\ProductController::single

main_categories:
    path:
        /{_locale}/categories
    requirements:
        _locale: "%locales%"
    controller: App\Controller\CategoryController::mainCategories

blog_index:
    path:
        /{_locale}/blog
    requirements:
        _locale: "%locales%"
    controller: App\Controller\BlogController::index
blog_post:
    path:
        /{_locale}/blog/{slug}
    requirements:
        _locale: "%locales%"
    controller: App\Controller\BlogController::post
checkout_index:
    path:
        /{_locale}/checkout
    requirements:
        _locale: "%locales%"
    controller: App\Controller\CheckoutController::index
paypal_pay:
    path:
        /paypal/pay/{orderHash}
    controller: App\Controller\PayController::paypalPay
orders_history:
    path:
        /{_locale}/history
    requirements:
        _locale: "%locales%"
    controller: App\Controller\CheckoutController::history
about_us:
    path:
        /{_locale}/about
    requirements:
        _locale: "%locales%"
    controller: App\Controller\CommonPagesController::aboutUs
shipping_and_payment:
    path:
        /{_locale}/shipping_and_payment
    requirements:
        _locale: "%locales%"
    controller: App\Controller\CommonPagesController::shippingAndPayment
contacts:
    path:
        /{_locale}/contacts
    requirements:
        _locale: "%locales%"
    controller: App\Controller\CommonPagesController::contacts
######cart#####
api_cart_all:
    methods: POST
    path: /api/cart/all
    controller: App\Controller\Api\CartController::all
api_cart_add:
    methods: POST
    path: /api/cart/add
    controller: App\Controller\Api\CartController::add
api_cart_minus:
    methods: POST
    path: /api/cart/minus
    controller: App\Controller\Api\CartController::minus
api_cart_remove:
    methods: POST
    path: /api/cart/remove
    controller: App\Controller\Api\CartController::remove
api_address_search:
    methods: POST
    path: /api/search
    controller: App\Controller\Api\SearchAddressController::search
api_checkout:
    methods: POST
    path: /api/checkout
    controller: App\Controller\Api\CheckoutController::checkout
api_paypal_callback:
    methods: GET
    path: /api/paypal/callback/{orderId}/{paypalId}
    controller: App\Controller\Api\PayController::handlePayPalCallback

#admin_panel
admin_index:
    path: /admin_panel
    controller: App\Controller\Admin\HomeController::index
admin_index_show:
    path: /admin_panel/home
    controller: App\Controller\Admin\HomeController::show
####API####
admin_api_specification_create:
    path: /api/specification/create
    controller: App\Controller\Api\SpecificationController::create
    methods:
        POST
####category###
admin_category_index:
    path: /admin_panel/category
    controller: App\Controller\Admin\CategoryController::index
admin_category_create:
    path: /admin_panel/category/create
    controller: App\Controller\Admin\CategoryController::create
admin_category_update:
    path: /admin_panel/category/update/{id}
    controller: App\Controller\Admin\CategoryController::update
admin_category_remove:
    path: /admin_panel/category/remove/{id}
    controller: App\Controller\Admin\CategoryController::remove
admin_category_show_on_main:
    path: /admin_panel/category/show_on_main
    controller: App\Controller\Admin\CategoryController::showOnMain
####product###
admin_product_index:
    path: /admin_panel/product
    controller: App\Controller\Admin\ProductController::index
admin_product_create:
    path: /admin_panel/product/create
    controller: App\Controller\Admin\ProductController::create
admin_product_update:
    path: /admin_panel/product/update/{id}
    controller: App\Controller\Admin\ProductController::update
admin_product_remove:
    path: /admin_panel/product/remove/{id}
    controller: App\Controller\Admin\ProductController::remove
admin_product_show_on_main:
    path: /admin_panel/product/show_on_main
    controller: App\Controller\Admin\ProductController::showOnMain
admin_api_product_switch-visibility:
    path: /api/product/switch-visibility
    controller: App\Controller\Admin\ProductController::switchVisibility
####article###
admin_article_index:
    path: /admin_panel/article
    controller: App\Controller\Admin\ArticleController::index
admin_article_create:
    path: /admin_panel/article/create
    controller: App\Controller\Admin\ArticleController::create
admin_article_update:
    path: /admin_panel/article/update/{id}
    controller: App\Controller\Admin\ArticleController::update
admin_article_remove:
    path: /admin_panel/article/remove/{id}
    controller: App\Controller\Admin\ArticleController::remove
####main_page_slider###
admin_main_page_slider_index:
    path: /admin_panel/main_page_slider
    controller: App\Controller\Admin\MainPageSliderController::index
admin_main_page_slider_create:
    path: /admin_panel/main_page_slider/create
    controller: App\Controller\Admin\MainPageSliderController::create
admin_main_page_slider_update:
    path: /admin_panel/main_page_slider/update/{id}
    controller: App\Controller\Admin\MainPageSliderController::update
admin_main_page_slider_remove:
    path: /admin_panel/main_page_slider/remove/{id}
    controller: App\Controller\Admin\MainPageSliderController::remove
######settings########
admin_settings_index:
    path: /admin_panel/settings
    controller: App\Controller\Admin\SettingsController::index
admin_setting_update:
    path: /admin_panel/settings/update
    controller: App\Controller\Admin\SettingsController::update

######orders########
admin_orders_index:
    path: /admin_panel/orders
    controller: App\Controller\Admin\OrdersController::index
admin_orders_update:
    path: /admin_panel/orders/show/{id}
    controller: App\Controller\Admin\OrdersController::show
admin_orders_change_status:
    path: /admin_panel/orders/change_status/{id}/{status}
    controller: App\Controller\Admin\OrdersController::changeStatus

#######sitemap#######
admin_sitemap_generate:
    path: /admin_panel/sitemap/generate
    controller: App\Controller\Admin\SitemapController::generate

#########robots.txt#######
admin_robotsTxt_update:
    path: /admin_panel/robots/update
    controller: App\Controller\Admin\SitemapController::uploadRobotsTxt

