index:
    path: /
    controller: App\Controller\IndexController::index


#admin_panel
admin_index:
    path: /admin_panel
    controller: App\Controller\Admin\HomeController::index
admin_index_show:
    path: /admin_panel/home
    controller: App\Controller\Admin\HomeController::show
####category###
admin_category_index:
    path: /admin_panel/category
    controller: App\Controller\Admin\CategoryController::index
admin_category_create:
    path: /admin_panel/category/create
    controller: App\Controller\Admin\CategoryController::create
admin_category_update:
    path: /admin_panel/category/update/{id}
    controller: App\Controller\Admin\CategoryController::update
admin_category_remove:
    path: /admin_panel/category/remove/{id}
    controller: App\Controller\Admin\CategoryController::remove
####product###
admin_product_index:
    path: /admin_panel/product
    controller: App\Controller\Admin\ProductController::index
admin_product_create:
    path: /admin_panel/product/create
    controller: App\Controller\Admin\ProductController::create
admin_product_update:
    path: /admin_panel/product/update/{id}
    controller: App\Controller\Admin\ProductController::update
admin_product_remove:
    path: /admin_panel/product/remove/{id}
    controller: App\Controller\Admin\ProductController::remove