index:
    path: /{_locale}
    defaults:
        _locale: "%locale%"
    requirements:
        _locale: "%locales%"
    controller: App\Controller\IndexController::index

######cart#####
api_cart_add:
    path: /api/cart/add
    controller: App\Controller\Api\CartController::add

single_product:
    path: /product
    controller: App\Controller\IndexController::singleProduct

#admin_panel
admin_index:
    path: /admin_panel
    controller: App\Controller\Admin\HomeController::index
admin_index_show:
    path: /admin_panel/home
    controller: App\Controller\Admin\HomeController::show
####API####
admin_api_specification_create:
    path: /api/specification/create
    controller: App\Controller\Api\SpecificationController::create
    methods:
        POST
####category###
admin_category_index:
    path: /admin_panel/category
    controller: App\Controller\Admin\CategoryController::index
admin_category_create:
    path: /admin_panel/category/create
    controller: App\Controller\Admin\CategoryController::create
admin_category_update:
    path: /admin_panel/category/update/{id}
    controller: App\Controller\Admin\CategoryController::update
admin_category_remove:
    path: /admin_panel/category/remove/{id}
    controller: App\Controller\Admin\CategoryController::remove
admin_category_show_on_main:
    path: /admin_panel/category/show_on_main
    controller: App\Controller\Admin\CategoryController::showOnMain
####product###
admin_product_index:
    path: /admin_panel/product
    controller: App\Controller\Admin\ProductController::index
admin_product_create:
    path: /admin_panel/product/create
    controller: App\Controller\Admin\ProductController::create
admin_product_update:
    path: /admin_panel/product/update/{id}
    controller: App\Controller\Admin\ProductController::update
admin_product_remove:
    path: /admin_panel/product/remove/{id}
    controller: App\Controller\Admin\ProductController::remove
admin_product_show_on_main:
    path: /admin_panel/product/show_on_main
    controller: App\Controller\Admin\ProductController::showOnMain
admin_api_product_switch-visibility:
    path: /api/product/switch-visibility
    controller: App\Controller\Admin\ProductController::switchVisibility
####article###
admin_article_index:
    path: /admin_panel/article
    controller: App\Controller\Admin\ArticleController::index
admin_article_create:
    path: /admin_panel/article/create
    controller: App\Controller\Admin\ArticleController::create
admin_article_update:
    path: /admin_panel/article/update/{id}
    controller: App\Controller\Admin\ArticleController::update
admin_article_remove:
    path: /admin_panel/article/remove/{id}
    controller: App\Controller\Admin\ArticleController::remove
####main_page_slider###
admin_main_page_slider_index:
    path: /admin_panel/main_page_slider
    controller: App\Controller\Admin\MainPageSliderController::index
admin_main_page_slider_create:
    path: /admin_panel/main_page_slider/create
    controller: App\Controller\Admin\MainPageSliderController::create
admin_main_page_slider_update:
    path: /admin_panel/main_page_slider/update/{id}
    controller: App\Controller\Admin\MainPageSliderController::update
admin_main_page_slider_remove:
    path: /admin_panel/main_page_slider/remove/{id}
    controller: App\Controller\Admin\MainPageSliderController::remove
