parameters:
    app.relative_uploads_dir: '/uploads/'
    app.uploads_dir: '%kernel.project_dir%/public%app.relative_uploads_dir%'
    locale: en
    locales: ru|en

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Strategy\Validation\ValidationStrategyInterface:
            tags: ['app.validation']

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\FileManager\FileManager:
        arguments:
            - '%app.uploads_dir%'
            - '%kernel.project_dir%/public'

    App\Service\CategoryService:
        arguments:
            - '%app.relative_uploads_dir%'

    App\Service\ProductService:
        arguments:
            - '%app.relative_uploads_dir%'

    App\Service\ArticleService:
        arguments:
            - '%app.relative_uploads_dir%'

    App\Service\MainPageSliderService:
        arguments:
            - '%app.relative_uploads_dir%'

    App\Service\ValidationService:
        arguments:
            - !tagged_iterator app.validation
