phone_RU:
  value: ''
  label: Телефон
phone_EN:
  value: ''
  label: Телефон
facebook_RU:
  value: ''
  label: 'Ссылка на facebook'
facebook_EN:
  value: ''
  label: 'Ссылка на facebook'
instagram_RU:
  value: ''
  label: 'Ссылка на instagram'
instagram_EN:
  value: ''
  label: 'Ссылка на instagram'
