phone_RU:
  value: ''
  label: Телефон
phone_EN:
  value: ''
  label: Телефон
facebook_RU:
  value: ''
  label: 'Ссылка на facebook'
facebook_EN:
  value: ''
  label: 'Ссылка на facebook'
instagram_RU:
  value: ''
  label: 'Ссылка на instagram'
instagram_EN:
  value: ''
  label: 'Ссылка на instagram'
about_us_EN:
  value: ''
  label: 'О нас'
  text_editor: true
about_us_RU:
  value: ''
  label: 'О нас'
  text_editor: true
address_EN:
  value: ''
  label: 'Адрес'
address_RU:
  value: ''
  label: 'Адрес'
schedule_EN:
  value: ''
  label: 'График работы'
  text_editor: true
schedule_RU:
  value: ''
  label: 'График работы'
  text_editor: true
shipping_EN:
  value: ''
  label: 'Оплата и доставка'
  text_editor: true
shipping_RU:
  value: ''
  label: 'Оплата и доставка'
  text_editor: true
home_page_title_RU:
  value: ''
  label: 'Сео тайтл на главной'
home_page_title_EN:
  value: ''
  label: 'Сео тайтл на главной'
home_page_description_RU:
  value: ''
  label: 'Сео описание на главной'
home_page_description_EN:
  value: ''
  label: 'Сео описание на главной'
categories_title_RU:
  value: ''
  label: 'Сео тайтл в категориях'
categories_title_EN:
  value: ''
  label: 'Сео тайтл в категориях'
categories_description_RU:
  value: ''
  label: 'Сео описание в категориях'
categories_description_EN:
  value: ''
  label: 'Сео описание в категориях'
about_us_title_RU:
  value: ''
  label: 'Сео тайтл "О нас"'
about_us_title_EN:
  value: ''
  label: 'Сео тайтл "О нас"'
about_us_description_RU:
  value: ''
  label: 'Сео описание "О нас"'
about_us_description_EN:
  value: ''
  label: 'Сео описание "О нас"'
blog_title_RU:
  value: ''
  label: 'Сео тайтл в блоге'
blog_title_EN:
  value: ''
  label: 'Сео тайтл в блоге'
blog_description_RU:
  value: ''
  label: 'Сео описание в блоге'
blog_description_EN:
  value: ''
  label: 'Сео описание в блоге'
shipping_title_RU:
  value: ''
  label: 'Сео тайтл в "Деталях доставки"'
shipping_title_EN:
  value: ''
  label: 'Сео тайтл в "Деталях доставки"'
shipping_description_RU:
  value: ''
  label: 'Сео описание в "Деталях доставки"'
shipping_description_EN:
  value: ''
  label: 'Сео описание в "Деталях доставки"'