phone_RU:
    value: кцщуц
    label: Телефон
phone_EN:
    value: '+380992770952'
    label: Телефон
facebook_RU:
    value: 'https://facefwefwebook.com'
    label: 'Ссылка на facebook'
facebook_EN:
    value: 'https://facebook.comfwfew'
    label: 'Ссылка на facebook'
instagram_RU:
    value: 'https://instagram.com'
    label: 'Ссылка на instagram'
instagram_EN:
    value: 'https://instagram.com'
    label: 'Ссылка на instagram'
